name: ESLint

on:
  push:
    branches:
      - dev/dashboard
  pull_request:
    branches: 
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20.13.1'

    - name: Install dependencies
      run: |
        yarn install

    - name: Run ESLint
      run: |
        yarn lint --config .github/linters/.eslintrc.cjs --max-warnings=0
